### PR TITLE
Making si_swapinfo exportable

### PR DESCRIPTION
**Pull request by Herrie82**
If we will make si_swapinfo() exportable it could be called from modules.
Otherwise modules have no interface to obtain information about swap usage.
Change made in the same way as si_meminfo() declared.

Signed-off-by: Leonid Moiseichuk <leonid.moiseichuk@nokia.com>
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by Herrie82** [comment]
This is needed for https://github.com/webOS-ports/memnotify-module

**Comment by piggz** [comment]
thanks for these.  I'll have to test the paranoid network change, it is supposed to now work automatically with sailfish these days so I expect it to be ok.

**Comment by Herrie82** [comment]
Sorry those last 3 shouldn't have ended up here. Only the first one... Should've made a separate branch for these so they wouldn't end up in this PR. It's mainly about the "Making si_swapinfo exportable" for now.

**Comment by Herrie82** [comment]
Will send new one

**Pull request closed without merging**
